name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd online_ide
            git pull origin main

            echo "Building Go server..."
            cd sever
            go build main.go
            chmod +x main
            sudo systemctl restart go-online-ide.service

            echo "Building Vite client..."
            cd ../client
            sudo rm -rf node_modules
            sudo rm -rf dist
            npm ci
            npm run build

            echo "Restarting NGINX..."
            sudo systemctl restart nginx
